### PR TITLE
Fixes an ArrayIndexOutOfBoundsException in ItemStackResponseStatus

### LINKED ISSUE #317: ItemStackResponse Error
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 49 out of bounds for length 2
        at org.cloudburstmc.protocol.bedrock.codec.v419.serializer.ItemStackResponseSerializer_v419.lambda$deserialize$1(ItemStackResponseSerializer_v419.java:37) ~[bedrock-codec-3.0.0.Beta11-20251209.183710-13.jar:?]
```

The packet now sends an ID from the ItemStackNetResult enum

https://mojang.github.io/bedrock-protocol-docs/html/enums.html

### PR DESCRIPTION
**Pull request by Exterminate5573**
Fixes #317

### CODE REVIEW

**Comment by Exterminate5573** [comment]
Rough fix so I could continue development on Viabedrock

File: bedrock-codec/src/main/java/org/cloudburstmc/protocol/bedrock/data/inventory/itemstack/response/ItemStackResponseStatus.java [hunk 1]
```diff
@@ -4,13 +4,72 @@
...
-    /**
-     * The transaction request was valid.
-     */
-    OK,
-
-    /**
-     * The transaction request was invalid.
-     */
-    ERROR
+    Success,
```
Comment (PetteriM1) [inline bedrock-codec/src/main/java/org/cloudburstmc/protocol/bedrock/data/inventory/itemstack/response/ItemStackResponseStatus.java]: Can we keep the original name for this for backwards compatibility and also follow VALUE_NAME naming style to be consistent with the rest of the project?

**Review by PetteriM1 — APPROVED** [review]
